name: Update Cloudflare TXT Record

on:
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Environment Variables
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_RECORD_ID: ${{ secrets.CF_RECORD_ID }}
        CF_NAME: ${{ secrets.CF_NAME }}
      run: |
        echo "CF_API_TOKEN=${CF_API_TOKEN}"
        echo "CF_ZONE_ID=${CF_ZONE_ID}"
        echo "CF_RECORD_ID=${CF_RECORD_ID}"
        echo "CF_NAME=${CF_NAME}"

    - name: Update Cloudflare TXT Record
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_RECORD_ID: ${{ secrets.CF_RECORD_ID }}
        CF_NAME: ${{ secrets.CF_NAME }}
      run: |
        curl -X PUT "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/dns_records/${CF_RECORD_ID}" \
        -H "Authorization: Bearer ${CF_API_TOKEN}" \
        -H "Content-Type: application/json" \
        --data '{"type":"TXT","name":"${CF_NAME}","content":"re-test","ttl":120,"proxied":false}'
        
    - name: Sleep for 2 minutes
      run: sleep 120

    - name: Script completed
      run: echo "Script completed."
